### ISSUE TITLE
Smart mode can't be prevented from auto start

### ISSUE THREAD

**Issue by stsh89** [idbrii/vim-searchsavvy#3]
**Do you want to request a feature or report a bug?**

bug

**What is the current behavior?**

Placing  `let g:searchsavvy_smartgrep_auto_enable = 0` into .vimrc file not preventing from smart mode enabling.

**What is the expected behavior?**

Placing `let g:searchsavvy_smartgrep_auto_enable = 0` into .vimrc file should prevent smart mode enabling.

**Notes**

Maybe it can be fixed by changing 45 line in plugin/smartgrep.vim just by adding some condition like this:
```
if g:searchsavvy_smartgrep_auto_enable
    call SmartGrepToggle(g:searchsavvy_smartgrep_auto_enable)
endif
```

**Comment by idbrii** [comment]
Thanks for the report!
