### ISSUE TITLE
ClearAllButMatches clears other matches in the same line

### ISSUE THREAD

**Issue by aleksandargosevski** [idbrii/vim-searchsavvy#4]
Problem is when we search for multiple things, for example

```
This is one stupid example
```

and I search for `\(stupid\)\|\(example\)` which will match both stupid and example, ClearAllButMatches command will delete example, even though that's part of the match.

**Comment by idbrii** [comment]
File contains:
This is one stupid example
```
/\(stupid\)\|\(example\)
:ClearAllButMatches
```
File contains:
stupid
example

That's as desired, yes?

I'm on 706839044e326c0910f05543fabd3530a99ca9e4

Can you give a test case of vim commands to better see what's going wrong? Also are you at HEAD?

**Comment by goschevski** [comment]
Here is the demo - https://asciinema.org/a/0ern5pdo4mghlp1n2l464u6hh

**Comment by idbrii** [comment]
Build [passes on travis](https://travis-ci.org/idbrii/vim-searchsavvy). Can you try using a bare config?

You may want to binary search through your plugins to see what's interfering.


As far as I remember, this has worked correctly since vim 7.3, so I don't think it's vim. I'd guess there's something (gdefault, etc) that's special in your config that's breaking things.

**Comment by goschevski** [comment]
You're right! When I removed `set gdefault` from my vimrc it worked.

Is it possible to bypass this somehow since I would like to keep gdefault in my vimrc?

**Comment by idbrii** [comment]
It's not currently possible aside from making a command to set gdefault to defaults, call ClearAllButMatches, and set gdefault back to normal.

That set-and-restore could also be done inside ClearAllButMatches if you'd like to make a pull request.

**Comment by goschevski** [comment]
I don't have experience with vim script... I will have to do it in my `vimrc`, sorry about that.

Thanks!

**Comment by idbrii** [comment]
No problem. You could put something like this in your vimrc:

    function s:ClearAllButMatches_withgdefault()
        set gdefault&
        ClearAllButMatches
        set gdefault
    endfunction

    command MyClearAllButMatches call s:ClearAllButMatches_withgdefault()

**Comment by goschevski** [comment]
Thanks!
